
DRIVERS_DIR :=  src/core/drivers/K64

#add the K64 driver directory to the include path;
COMPIL_INC += $(DRIVERS_DIR)

#Add driver core source files;
DRIVER_SRCS +=  $(DRIVERS_DIR)/K64_PIT.c
DRIVER_SRCS +=  $(DRIVERS_DIR)/K64_PORT.c
DRIVER_SRCS +=  $(DRIVERS_DIR)/K64_UART.c
