//
// Created by root on 10/17/18.
//

#ifndef TRACER_FLOAT_H
#define TRACER_FLOAT_H

#include "type.h"


/*
 * Basic ops, chained ops, and conversion are directly generated by the compiler. Creating an abstraction over it
 * 	would reduce performances;
 */

//The square root;
f32_t f32_sqrt(f32_t);


#endif //TRACER_FLOAT_H
