
DRIVERS_DIR :=  src/hardware/drivers/K64

#add the K64 driver directory to the include path;
COMPIL_INC += $(DRIVERS_DIR)

#Add driver core source files;
CORE_SOURCES +=  $(DRIVERS_DIR)/K64_PIT.c
CORE_SOURCES +=  $(DRIVERS_DIR)/K64_PORT.c
CORE_SOURCES +=  $(DRIVERS_DIR)/K64_UART.c
