
COMPILERPATH ?= /usr/bin

# names for the compiler programs
CC = $(abspath $(COMPILERPATH))/arm-none-eabi-gcc
AR = $(abspath $(COMPILERPATH))/arm-none-eabi-gcc-ar
OBJCOPY = $(abspath $(COMPILERPATH))/arm-none-eabi-objcopy
SIZE = $(abspath $(COMPILERPATH))/arm-none-eabi-size
