
SS = src/std
SB = build/stdl

stdlib : 

	@$(_CC) -o $(SB)/list.o -c $(SS)/list.c
	@$(_CC) -o $(SB)/mem.o -c $(SS)/mem.c
	@$(_CC) -o $(SB)/stdout.o -c $(SS)/stdout.c
	@$(_CC) -o $(SB)/string.o -c $(SS)/string.c

STDL_RULES += stdlib